AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 160

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 1500

Metrics/ModuleLength:
  Max: 1500

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 17

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Naming/FileName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false
